[workspace]

members = [
    "crates/ruuster-server",
    "crates/ruuster-internals",
    "crates/ruuster-protos",
    "crates/ruuster-core",
    "crates/ruuster-router",
    "crates/ruuster-acks"
]

resolver = "2"
