[package]
name = "ruuster-protos"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.14.2"
prost = "0.14"
tonic-prost = "0.14.2"
prost-types = "0.14.2"

[build-dependencies]
tonic-prost-build = "0.14.2"
